apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: php-apache
          image: php:apache
          ports:
            - containerPort: 80
            # - containerPort: 443
          volumeMounts:
            - name: content
              mountPath: /var/www/html
      volumes:
        - name: content
          hostPath:
            path: /var/trisomie21/
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
      # protocol: TCP
    # - name: https
    #   protocol: TCP
    #   port: 443
  type: LoadBalancer
  # type: NodePort
status:
  loadBalancer: {}
